### PR TITLE
Services logs in JSON format

### LINKED ISSUE #360: Convert ingest to json log output
- For golang projects this should preferably be done using `log.SetFormatter(&log.JSONFormatter{})`. 
- Numerical values that are important for the log message should be broken out into separate json fields for easy parsing.
- Log messages should only use the "info" level messages that are to be used in graphana. 

ex. 
```
{"msg": "file <name> uploaded", "level": "info", "rate": 28912.51, "size": 769154871}
```
can be used to monitor upload speed and size, while:
```
{"msg": "file <name> verified", "level": "info"}
```
should be a `debug` message, as we are planning to fetch file status events from the postgres database.

### LINKED ISSUE #361: Convert intercept to json log output
- For golang projects this should preferably be done using `log.SetFormatter(&log.JSONFormatter{})`. 
- Numerical values that are important for the log message should be broken out into separate json fields for easy parsing.
- Log messages should only use the "info" level messages that are to be used in graphana. 

ex. 
```
{"msg": "file <name> uploaded", "level": "info", "rate": 28912.51, "size": 769154871}
```
can be used to monitor upload speed and size, while:
```
{"msg": "file <name> verified", "level": "info"}
```
should be a `debug` message, as we are planning to fetch file status events from the postgres database.

### LINKED ISSUE #362: Convert mapper to json log output
- For golang projects this should preferably be done using `log.SetFormatter(&log.JSONFormatter{})`. 
- Numerical values that are important for the log message should be broken out into separate json fields for easy parsing.
- Log messages should only use the "info" level messages that are to be used in graphana. 

ex. 
```
{"msg": "file <name> uploaded", "level": "info", "rate": 28912.51, "size": 769154871}
```
can be used to monitor upload speed and size, while:
```
{"msg": "file <name> verified", "level": "info"}
```
should be a `debug` message, as we are planning to fetch file status events from the postgres database.

### LINKED ISSUE #363: Convert verify to json log output
- For golang projects this should preferably be done using `log.SetFormatter(&log.JSONFormatter{})`. 
- Numerical values that are important for the log message should be broken out into separate json fields for easy parsing.
- Log messages should only use the "info" level messages that are to be used in graphana. 

ex. 
```
{"msg": "file <name> uploaded", "level": "info", "rate": 28912.51, "size": 769154871}
```
can be used to monitor upload speed and size, while:
```
{"msg": "file <name> verified", "level": "info"}
```
should be a `debug` message, as we are planning to fetch file status events from the postgres database.

### PR DESCRIPTION
**Pull request by kostas-kou**
Change the logs format to json for the services in order to be easier to parse with grafana

Closes #361, Closes #360, Closes #362, Closes #363

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -33,6 +33,11 @@ type Config struct {
 	Database database.DBConf
 }
 
+func init() {
+	// Convert logs to JSON format in all teh services
```
Comment (blankdots) [inline internal/config/config.go:37]:
```suggestion
	// Convert logs to JSON format in all the services
```

**Review by blankdots — COMMENTED** [review]
does this solve #360 #361 #362 and #363 ?

**Comment by kjellp** [comment]
> 
> should we make this configurable with a config e.g. `log.format` which can be `json` or `text` and we default to `json` ?

We second that from Norway. Would be good to choose at config time.

**Review by a-ghanem — APPROVED** [review]

File: internal/config/config.go [hunk 2]
```diff
@@ -33,6 +33,11 @@ type Config struct {
 	Database database.DBConf
 }
 
+func init() {
+	// Convert logs to JSON format in all the services
+	log.SetFormatter(&log.JSONFormatter{})
+}
+
```
Comment (jbygdell) [inline internal/config/config.go:40]: Place this in the `NewConfig` block.
It would also be nice to make it configurable so that the users can switch at their own pace since this is directly related to how logging is stored and parsed.

**Review by jbygdell — CHANGES_REQUESTED** [review]

**Review by blankdots — APPROVED** [review]

**Review by jbygdell — APPROVED** [review]

**Review by dbampalikis — APPROVED** [review]
