### PR TITLE
Bail out earlier on problems

### LINKED ISSUE #110: Fail on startup if c4gh keyfile can not be opended

### PR DESCRIPTION
**Pull request by pontus**
Moved some things that can be reused so they are initialized before the main loop. Also, verify storage backends upon creation.

Fixes #110, #111 and #112.

This currently uses ListObjectsV2 from s3 and requires that not to fail. That adds a requirement for s3 backends to have read permissions to the bucket. I believe that is acceptable (but worth mentioning especially).

### CODE REVIEW

File: cmd/verify/verify.go [hunk 1]
```diff
@@ -214,3 +210,20 @@ func main() {
...
+	}
+
+	key, err := keys.ReadPrivateKey(keyFile, []byte(conf.Passphrase))
+	if err != nil {
+		return nil, err
+	}
+
+	keyFile.Close()
+	return &key, nil
+}
```
Comment (jbygdell) [inline cmd/verify/verify.go:229]: same here, better put it in config.go

File: internal/storage/storage.go [hunk 2]
```diff
@@ -143,18 +165,30 @@ func newS3Backend(config S3Conf) *s3Backend {
...
+
+	return sb, nil
 }
 
 // NewFileReader returns an io.Reader instance
 func (sb *s3Backend) NewFileReader(filePath string) (io.ReadCloser, error) {
+	if sb == nil {
+		return nil, fmt.Errorf("Invalid s3Backend")
+	}
+
```
Comment (jbygdell) [inline internal/storage/storage.go:191]: Is this necessary?An invalid back-end should have been caught at startup and prevented this point from being reached.

File: internal/storage/storage.go [hunk 3]
```diff
@@ -170,6 +204,10 @@ func (sb *s3Backend) NewFileReader(filePath string) (io.ReadCloser, error) {
 
 // NewFileWriter uploads the contents of an io.Reader to a S3 bucket
 func (sb *s3Backend) NewFileWriter(filePath string) (io.WriteCloser, error) {
+	if sb == nil {
+		return nil, fmt.Errorf("Invalid s3Backend")
+	}
+
```
Comment (jbygdell) [inline internal/storage/storage.go:210]: Is this necessary?An invalid back-end should have been caught at startup and prevented this point from being reached.

File: internal/storage/storage.go [hunk 4]
```diff
@@ -187,6 +225,10 @@ func (sb *s3Backend) NewFileWriter(filePath string) (io.WriteCloser, error) {
 
 // GetFileSize returns the size of a specific object
 func (sb *s3Backend) GetFileSize(filePath string) (int64, error) {
+	if sb == nil {
+		return 0, fmt.Errorf("Invalid s3Backend")
+	}
+
```
Comment (jbygdell) [inline internal/storage/storage.go:231]: Is this necessary?An invalid back-end should have been caught at startup and prevented this point from being reached.

**Review by jbygdell — CHANGES_REQUESTED** [review]

File: cmd/verify/verify.go (hunk 1 above)
Comment (pontus) [reply cmd/verify/verify.go]: Fixed similarly.

File: cmd/ingest/ingest.go [hunk 5]
```diff
@@ -249,21 +263,29 @@ func main() {
...
+
+	key, err := keys.ReadPrivateKey(keyFile, []byte(conf.Passphrase))
 	if err != nil {
-		log.Error(err)
 		return nil, err
 	}
+
+	keyFile.Close()
+	return &key, nil
+}
```
[the remark this answers is not in the document]
Comment (pontus) [reply cmd/ingest/ingest.go]: Yep, mostly went for minimal refactoring. Moved to config now (would also be happy to but in a separate package, but either's fine).

File: internal/storage/storage.go (hunk 2 above)
Comment (pontus) [reply internal/storage/storage.go:191]: Should (of course) not be needed, no. With that said, these are cheap in the normal case and simplifies test writing a bit (or rather understanding if things fail).

My understanding of what happened is that a later crash made the prior assert not show so it took longer than it should have to figure out what happened.

I have a slight preference for leaving them because of that but am totally fine with pulling them out if you don't like them.

Comment (jonandernovella) [reply internal/storage/storage.go:191]: As far as I know, it is a good practice to have this. It is not a crucial component, but still makes sure that you can track down the error better.

File: cmd/ingest/ingest.go [hunk 6]
```diff
@@ -61,6 +59,23 @@ func main() {
 		log.Fatal(err)
 	}
 
+	key, err := config.GetC4GHKey()
+	if err != nil {
+		log.Fatal(err)
+	}
```
Comment (jbygdell) [inline cmd/ingest/ingest.go:65]: Putting the comment here as the code is spread out a bit.

The reason we didn't do it this way initially was to mitigate one of the flaws in the python version, that the key is always unlocked when the app is running.

That's why I suggested moving the unlocking of the key to the `config` part, since it is used by more than one component, while still returning the keypath and the passphrase to the app. That way we test that the key can be unlocked and we fail early if it can't. But we only unlock it when it is time to use it.

Comment (pontus) [reply cmd/ingest/ingest.go:65]: I don't have a strong opinion on keeping a single key fetch, but I don't see that helping security much (for most attacks, it's likely that the attacker has access to the file and can more easily grab the passphrase from the environment than analyze a memory dump to try to locate something that looks like a key).

If we move it back inside the loop, we might as well clear the array used for the key when we're done with it.

**Comment by jbygdell** [comment]
Needs to be rebased ontop of master.

**Review by jbygdell — APPROVED** [review]

**Review by blankdots — APPROVED** [review]
